name: Cypress Test Automation

on:
  pull_request:
    branches: ["main", "development"]

jobs:
  cypress-old-ghost-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"

      - name: Run tests
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -- --spec 'cypress/e2e/v3.41.1/scenarios/*.cy.js'
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: old-ghost-version-files
          path: src/cypressTests/cypress/screenshots/${{steps.date.outputs.time}}/v3.41.1

  cypress-new-ghost-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -- --spec 'cypress/e2e/v4.44.0/scenarios/*.cy.js'
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: new-ghost-version-files
          path: src/cypressTests/cypress/screenshots/${{steps.date.outputs.time}}/v4.44.0

  cypress-vrt-report:
    runs-on: ubuntu-latest
    needs: [cypress-old-ghost-version]
    environment:
      name: github-pages-deployment
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY-MM-DD"
    - uses: actions/checkout@v3
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - run: ls && pwd
    - run: cd old-ghost-version-files && ls
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3s
      with:
        node-version: "18.x"
        cache: "npm"
    - run: npm ci
    - run: npm run build --if-present
    - run: ls && pwd
    - run: cd ./src/ && ls && pwd
    - run: npm run report -- src/old-ghost-version-files src/new-ghost-version-files
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './VRTReports/${{steps.date.outputs.time}}/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
