name: Cypress Test Automation

on:
  pull_request:
    branches: ["main", "development"]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v3
      - name: Run tests
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: node ./src/reportScript/script.js '/home/runner/work/ghost-e2e/ghost-e2e/src/cypressTests/cypress/screenshots/${{steps.date.outputs.date}}/3.41.1' '/home/runner/work/ghost-e2e/ghost-e2e/src/cypressTests/cypress/screenshots/${{steps.date.outputs.date}}/4.44.0'
