name: Cypress Test Automation

on:
  pull_request:
    branches: ["main", "development"]

jobs:
  cypress-old-ghost-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"

      - name: Run tests
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -- --spec 'cypress/e2e/v3.41.1/scenarios/*.cy.js'
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: old-ghost-version-files
          path: src/cypressTests/cypress/screenshots/${{steps.date.outputs.time}}/v3.41.1/

  cypress-new-ghost-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -- --spec 'cypress/e2e/v4.44.0/scenarios/*.cy.js'
        continue-on-error: true
      - run: ls -la && pwd
      - uses: actions/upload-artifact@v3
        with:
          name: new-ghost-version-files
          path: src/cypressTests/cypress/screenshots/${{steps.date.outputs.time}}/v4.44.0

  cypress-vrt-report:
    runs-on: ubuntu-latest
    needs: [cypress-old-ghost-version, cypress-new-ghost-version]

    steps:
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY-MM-DD"
    - uses: actions/download-artifact@master
      with:
          name: old-ghost-version-files
          path: src/cypressTests/cypress/screenshots/${{steps.date.outputs.time}}/v3.41.1/
    - uses: actions/download-artifact@master
      with:
          name: new-ghost-version-files
          path: src/cypressTests/cypress/screenshots/${{steps.date.outputs.time}}/v4.44.0/
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        cache: "npm"
    - run: npm ci
    - run: npm run build --if-present
    - run: node ./src/reportScript/script.js src/cypressTests/cypress/screenshots/${{steps.date.outputs.time}}/v3.41.1 src/cypressTests/cypress/screenshots/${{steps.date.outputs.time}}/v4.44.0
